export interface Template {
  id: string; icon: string; name: string; desc: string; html: string;
}

const S = `*{box-sizing:border-box;margin:0;padding:0}body{font-family:system-ui,sans-serif;background:#0d0f12;color:#e2e8f0}`;

export const TEMPLATES: Template[] = [
  {
    id: 'blank', icon: '⬜', name: '空白画布', desc: '从零开始，完全自由',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>我的应用</title><style>${S}body{min-height:100vh;display:flex;align-items:center;justify-content:center}.c{text-align:center;padding:40px}.c h1{font-size:2.5rem;margin-bottom:16px;background:linear-gradient(135deg,#6366f1,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.c p{color:#64748b;font-size:1.1rem;line-height:1.7}</style></head><body><div class="c"><h1>👋 你好，世界</h1><p>在左侧对话框告诉 AI 你想要什么样的页面</p></div></body></html>`,
  },
  {
    id: 'landing', icon: '🚀', name: '产品落地页', desc: '展示卖点与行动按钮',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>产品落地页</title><style>${S}.hero{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:60px 24px;background:radial-gradient(ellipse at 50% 0%,#1a1d2e,#0d0f12 70%)}.hero h1{font-size:clamp(2rem,5vw,3.5rem);font-weight:800;background:linear-gradient(135deg,#6366f1,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:20px}.hero p{color:#94a3b8;font-size:1.2rem;max-width:560px;line-height:1.7;margin-bottom:32px}.btn{padding:14px 36px;background:linear-gradient(135deg,#6366f1,#4f46e5);color:#fff;border:none;border-radius:50px;font-size:1rem;font-weight:600;cursor:pointer;transition:.2s}.btn:hover{transform:translateY(-2px);box-shadow:0 8px 30px rgba(99,102,241,.4)}.feats{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;padding:60px 40px;max-width:960px;margin:0 auto}.feat{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:28px}.feat h3{margin-bottom:8px}.feat p{color:#64748b;font-size:.9rem}</style></head><body><section class="hero"><h1>下一代产品体验</h1><p>用最简单的方式完成最复杂的任务。立即开始您的旅程。</p><button class="btn">立即开始 →</button></section><section class="feats"><div class="feat"><h3>⚡ 极速体验</h3><p>毫秒级响应，边缘节点全球加速</p></div><div class="feat"><h3>🛡️ 安全可靠</h3><p>端到端加密，企业级安全保障</p></div><div class="feat"><h3>🎯 精准触达</h3><p>智能分析，精准触达目标用户</p></div></section></body></html>`,
  },
  {
    id: 'dashboard', icon: '📊', name: '数据看板', desc: '统计卡片与趋势图表',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>数据看板</title><style>${S}body{min-height:100vh;padding:32px}.hd{display:flex;justify-content:space-between;align-items:center;margin-bottom:32px}.hd h1{font-size:1.5rem;font-weight:700}.badge{background:#6366f1;color:#fff;padding:4px 12px;border-radius:20px;font-size:.8rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:20px;margin-bottom:32px}.card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:24px}.card .lbl{font-size:.85rem;color:#64748b;margin-bottom:8px}.card .val{font-size:2rem;font-weight:700;color:#e2e8f0}.card .trend{font-size:.8rem;color:#10b981;margin-top:6px}.chart{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:24px}.chart h2{font-size:1rem;margin-bottom:24px;color:#94a3b8}.bars{display:flex;align-items:flex-end;gap:8px;height:140px}.bar{flex:1;background:linear-gradient(to top,rgba(99,102,241,.2),#6366f1);border-radius:4px 4px 0 0;transition:.3s}.bar:hover{filter:brightness(1.3)}</style></head><body><div class="hd"><h1>📊 数据看板</h1><span class="badge">实时更新</span></div><div class="grid"><div class="card"><div class="lbl">总用户数</div><div class="val">24,521</div><div class="trend">↑ 12.4%</div></div><div class="card"><div class="lbl">今日收入</div><div class="val">¥8,840</div><div class="trend">↑ 7.2%</div></div><div class="card"><div class="lbl">活跃应用</div><div class="val">128</div><div class="trend">↑ 3.1%</div></div><div class="card"><div class="lbl">平均时延</div><div class="val">42ms</div><div class="trend">↓ 8.0%</div></div></div><div class="chart"><h2>最近 12 周请求量</h2><div class="bars"><div class="bar" style="height:50%"></div><div class="bar" style="height:65%"></div><div class="bar" style="height:45%"></div><div class="bar" style="height:80%"></div><div class="bar" style="height:60%"></div><div class="bar" style="height:90%"></div><div class="bar" style="height:70%"></div><div class="bar" style="height:85%"></div><div class="bar" style="height:55%"></div><div class="bar" style="height:95%"></div><div class="bar" style="height:75%"></div><div class="bar" style="height:100%"></div></div></div></body></html>`,
  },
  {
    id: 'ai-chat', icon: '🤖', name: 'AI 对话助手', desc: '内置 Claude 对话界面',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI 助手</title><style>${S}body{height:100vh;display:flex;flex-direction:column}.hd{padding:16px 24px;background:rgba(255,255,255,.04);border-bottom:1px solid rgba(255,255,255,.08);display:flex;align-items:center;gap:12px;font-weight:600}.dot{width:8px;height:8px;background:#10b981;border-radius:50%}.msgs{flex:1;overflow-y:auto;padding:24px;display:flex;flex-direction:column;gap:16px}.msg{max-width:80%;padding:14px 18px;border-radius:12px;line-height:1.6;font-size:.95rem}.msg.ai{background:rgba(99,102,241,.12);border:1px solid rgba(99,102,241,.2);align-self:flex-start;border-radius:4px 12px 12px 12px}.msg.user{background:linear-gradient(135deg,#6366f1,#4f46e5);align-self:flex-end;border-radius:12px 4px 12px 12px}.input-row{display:flex;gap:12px;padding:16px 24px;background:rgba(255,255,255,.03);border-top:1px solid rgba(255,255,255,.06)}.input-row input{flex:1;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:12px 16px;color:#e2e8f0;font-size:.95rem;outline:none}.input-row input:focus{border-color:#6366f1}.btn{padding:12px 24px;background:#6366f1;color:#fff;border:none;border-radius:12px;cursor:pointer;font-weight:600;transition:.2s}.btn:hover{background:#4f46e5}.btn:disabled{opacity:.5}</style></head><body><div class="hd"><div class="dot"></div>AI 对话助手</div><div class="msgs" id="msgs"><div class="msg ai">👋 你好！我是你的 AI 助手，有什么可以帮助你的？</div></div><div class="input-row"><input id="inp" placeholder="输入消息，按 Enter 发送..." /><button class="btn" id="btn">发送</button></div><script>const API='https://neo-proxy.feifeixp.workers.dev/api/chat';const msgs=[];async function send(){const inp=document.getElementById('inp');const v=inp.value.trim();if(!v)return;inp.value='';msgs.push({role:'user',content:v});render();document.getElementById('btn').disabled=true;try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:msgs,model:'claude-haiku-4-5',max_tokens:1024})});const d=await r.json();const t=d.content?.[0]?.text||'抱歉，出错了';msgs.push({role:'assistant',content:t});render();}catch(e){msgs.push({role:'assistant',content:'网络错误：'+e.message});render();}finally{document.getElementById('btn').disabled=false;}}function render(){const el=document.getElementById('msgs');el.innerHTML=msgs.map(m=>\`<div class="msg \${m.role==='user'?'user':'ai'}">\${m.content.replace(/</g,'&lt;')}</div>\`).join('');el.scrollTop=el.scrollHeight;}document.getElementById('inp').addEventListener('keydown',e=>e.key==='Enter'&&send());document.getElementById('btn').onclick=send;</script></body></html>`,
  },
  {
    id: 'countdown', icon: '⏱️', name: '倒计时活动页', desc: '带倒计时的活动宣传',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>倒计时</title><style>${S}body{min-height:100vh;display:flex;align-items:center;justify-content:center;background:radial-gradient(ellipse at center,#1a1d2e,#0d0f12);text-align:center;padding:40px}.wrap h2{font-size:1rem;color:#6366f1;letter-spacing:.2em;text-transform:uppercase;margin-bottom:16px}.wrap h1{font-size:clamp(2rem,4vw,3rem);font-weight:800;margin-bottom:48px}.cd{display:flex;gap:24px;justify-content:center;margin-bottom:48px}.unit{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:16px;padding:24px 28px;min-width:90px}.unit .n{font-size:2.8rem;font-weight:800;color:#6366f1;line-height:1}.unit .l{font-size:.8rem;color:#64748b;margin-top:6px;letter-spacing:.05em}.sub{color:#64748b;font-size:1rem}</style></head><body><div class="wrap"><h2>🎉 即将到来</h2><h1>新品发布倒计时</h1><div class="cd"><div class="unit"><div class="n" id="d">00</div><div class="l">天</div></div><div class="unit"><div class="n" id="h">00</div><div class="l">时</div></div><div class="unit"><div class="n" id="m">00</div><div class="l">分</div></div><div class="unit"><div class="n" id="s">00</div><div class="l">秒</div></div></div><p class="sub">敬请期待，精彩即将开始</p></div><script>const target=new Date();target.setDate(target.getDate()+7);function pad(n){return String(n).padStart(2,'0')}function tick(){const diff=Math.max(0,target-Date.now());const d=Math.floor(diff/864e5);const h=Math.floor(diff%864e5/36e5);const m=Math.floor(diff%36e5/6e4);const s=Math.floor(diff%6e4/1e3);document.getElementById('d').textContent=pad(d);document.getElementById('h').textContent=pad(h);document.getElementById('m').textContent=pad(m);document.getElementById('s').textContent=pad(s);}tick();setInterval(tick,1000);</script></body></html>`,
  },
  {
    id: 'tool', icon: '🛠️', name: '实用小工具', desc: '单位换算 / 文本处理等',
    html: `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>小工具</title><style>${S}body{min-height:100vh;padding:40px 24px}.wrap{max-width:640px;margin:0 auto}h1{font-size:1.5rem;font-weight:700;margin-bottom:32px}h1 span{color:#6366f1}.card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:28px;margin-bottom:20px}.card h2{font-size:1rem;color:#94a3b8;margin-bottom:16px}textarea,input{width:100%;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:12px;color:#e2e8f0;font-size:.95rem;outline:none;resize:vertical}.row{display:flex;gap:10px;margin-top:12px}button{padding:10px 20px;background:#6366f1;color:#fff;border:none;border-radius:10px;cursor:pointer;font-weight:600;transition:.2s}button:hover{background:#4f46e5}.out{margin-top:12px;padding:12px;background:rgba(0,0,0,.3);border-radius:8px;font-size:.9rem;color:#94a3b8;min-height:48px;word-break:break-all}</style></head><body><div class="wrap"><h1>🛠️ <span>实用</span>小工具</h1><div class="card"><h2>📝 文本统计</h2><textarea id="txt" rows="5" placeholder="在此粘贴文字..."></textarea><div class="out" id="stat">字符数：0 | 行数：0 | 词数：0</div></div><div class="card"><h2>🔗 URL 编解码</h2><input id="url" placeholder="输入需要编码 / 解码的 URL..."><div class="row"><button onclick="encodeUrl()">编码</button><button onclick="decodeUrl()">解码</button></div><div class="out" id="urlout">结果显示在这里...</div></div></div><script>document.getElementById('txt').addEventListener('input',function(){const v=this.value;document.getElementById('stat').textContent='字符数：'+v.length+' | 行数：'+(v?v.split('\n').length:0)+' | 词数：'+(v.trim()?v.trim().split(/\s+/).length:0);});function encodeUrl(){const v=document.getElementById('url').value;document.getElementById('urlout').textContent=encodeURIComponent(v);}function decodeUrl(){try{document.getElementById('urlout').textContent=decodeURIComponent(document.getElementById('url').value);}catch(e){document.getElementById('urlout').textContent='解码失败：'+e.message;}}</script></body></html>`,
  },
];

export function getTemplateById(id: string): Template {
  return TEMPLATES.find(t => t.id === id) ?? TEMPLATES[0];
}
